name: Automated tests on push

on:
  push

jobs:
  tests:
    runs-on: python:3.10.6-slim
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: set up and activate virtual environment
        run: |
          python3 -m pip install --upgrade pip
          python3 -m venv venv
          source venv/bin/activate
          python3 -m pip install --upgrade pip
      - name: install dependencies and project
        run: |
          pip install -r requirements.txt
          pip install -r requirements.dev.txt
          pip install -e .
      - name: lint test
        run: flake8 -v --benchmark
      - name: unit tests
        run: coverage run -m pytest && coverage report
